config/routes.rb
Rails.application.routes.draw do
  resources :movies, only: [:index, :show, :new, :create, :destroy]

  resources :lists, only: [:index, :show, :new, :create, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]

  root 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie, presence: true
  validates :list, presence: true
  validates :movie_id, uniqueness: { scope: :list_id, message: "is already in the list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = @list.bookmarks.build(bookmark_params)
    if @bookmark.save
      redirect_to @list, notice: 'Bookmark was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :destroy]

  def index
    @movies = Movie.all
  end

  def show
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to @movie, notice: 'Movie was successfully added.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @movie.destroy
    redirect_to movies_path, status: :see_other
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "movies/header" %>
    <div class="container mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<h1>My Lists</h1>

<div class="list-group" style="width: 500px;">
  <% @lists.each do |list| %>
  <%= link_to list.name, list_path(list), class: "list-group-item list-group-item-action" %>
  <% end %>
</div>

<%= link_to "Create a new list", new_list_path, class: "btn btn-primary mt-5" %>

app/views/lists/new.html.erb
<h1>Create a new list</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name, label: "List name:" %>
  <%= f.submit "Create List", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<p>Add list of movies here.</p>

  <%= link_to "All lists", lists_path, class: "btn btn-primary" %>
  <%= link_to "Delete this list",
    list_path(@list),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
    class: "btn btn-danger"
  %>

app/views/movies/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <%= link_to "WatchList", movies_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", movies_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Lists", lists_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add movie", new_movie_path, class: "nav-link" %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/movies/index.html.erb
<h1>All Movies (<%= @movies.count %>)</h1>

<div class="row justify-content-center">
    <% @movies.each do |movie| %>
      <div class="col-md-3 d-flex align-items-stretch mb-4">
        <div class="card" style="width: 18rem;">
          <img src="<%= movie.poster_url %>" class="card-img-top" alt="<%= movie.title %>" style="width: 100%; height: 200px; object-fit: cover;">
          <div class="card-body">
            <h5 class="card-title"><%= link_to movie.title, movie_path(movie), style: "color: black; text-decoration: none" %></h5>
            <p class="card-text"><%= movie.overview %></p>
          </div>
          <div class="card-footer">
            <small class="text-body-secondary"><i class="fa-regular fa-bookmark"></i> Bookmark</small>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/movies/new.html.erb
<h1>Add a movie</h1>

<%= simple_form_for @movie do |f| %>
  <%= f.input :title %>
  <%= f.input :overview %>
  <%= f.input :poster_url %>
  <%= f.input :rating %>
  <%= f.submit "Add Movie", class: "btn btn-primary" %>
<% end %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>

<img src="<%= @movie.poster_url %>" class="rounded float-start" alt="<%= @movie.title %>" style="max-width: 200px; object-fit: cover; margin-right: 20px;">

<p><%= @movie.overview %></p>

  <%= link_to "All movies", movies_path, class: "btn btn-primary" %>
  <%= link_to "Delete this movie",
    movie_path(@movie),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
    class: "btn btn-danger"
  %>